#!/usr/bin/env ruby

#
# ni2nih -- transform NI URI to NIH representation
#
# This is the NI URI library developed as
# part of the SAIL project. (http://sail-project.eu)
#
# Specification(s) - note, versions may change::
# * http://tools.ietf.org/html/farrell-decade-ni
# * http://tools.ietf.org/html/draft-hallambaker-decade-ni-params
#
# Author:: Dirk Kutscher <kutscher@neclab.eu>
# Copyright:: Copyright (c) 2012 Dirk Kutscher <kutscher@neclab.eu>
#
# License:: http://www.apache.org/licenses/LICENSE-2.0.html
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

$: << File.dirname(__FILE__)

require 'ni'
require 'getoptlong'

ni=nil
file=nil
web=nil

def printUsage
  print "Usage: ni2nih -n <name>\n"
  print "       ni2nih -h -- print usage info\n"
end



opts = GetoptLong.new(
  ['--help', '-h', GetoptLong::NO_ARGUMENT ],
  ['--ni', '-n', GetoptLong::REQUIRED_ARGUMENT ]
)

opts.each do |opt, arg|
  case opt
  when "--help"
    printUsage
    exit 0
  when "--ni"
    ni=arg
  end
end

u=URI::parse(ni)
#print ("Transforming #{ni.to_s}...\n")
print ("#{u.to_nih}\n")




