#!/usr/bin/env ruby

#
# searchni -- SEARCH NetInf objects over HTTT
#
# This is the NI URI library developed as
# part of the SAIL project. (http://sail-project.eu)
#
# Specification(s) - note, versions may change::
# * http://tools.ietf.org/html/farrell-decade-ni
# * http://tools.ietf.org/html/draft-hallambaker-decade-ni-params
#
# Author:: Dirk Kutscher <kutscher@neclab.eu>
# Copyright:: Copyright (c) 2012 Dirk Kutscher <kutscher@neclab.eu>
#
# License:: http://www.apache.org/licenses/LICENSE-2.0.html
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

$: << File.dirname(__FILE__)

require 'json'
require 'httpcl'
require 'getoptlong'
require 'net/http'

loc=nil
keywords=nil


def printUsage
  print "Usage: searchni -k <keywords> -l <FQDN> -- search node over HTTP\n"
  print "       searchni -h -- print usage info\n"
end


opts = GetoptLong.new(
                      ['--help', '-h', GetoptLong::NO_ARGUMENT ],
                      ['--keywords', '-k', GetoptLong::REQUIRED_ARGUMENT ],
                      ['--loc', '-l', GetoptLong::REQUIRED_ARGUMENT ]
)



opts.each do |opt, arg|
  case opt
  when "--help"
    printUsage
    exit 0
  when "--loc"
    loc=arg
  when "--keywords"
    keywords=arg
  end
end


if !loc
  printUsage()
  exit 1
end

nhttp=NetInfHTTP.new

msgId=Time.new.strftime("%Y%m%d%H%M%S")
res=nhttp.search(loc, msgId, keywords, false) # true: index
if res.code=="200"
#  print res.body
#  exit 0
  l=JSON::parse(res.body)
#  print "#{l}\n"
  results=l["results"]
#  print "#{results}\n"
  nr=1
  results.each { |r|
    name=r["ni"]
    print "#{nr}: #{name}\n"
    nr+=1
  }

  # if l.class==Array
  #   l.each { |n|
  #     print "#{n}\n"
  #   }
  # else
  #   print "parse error"
  # end
else
  print "error, got: #{res}\n"
  print "#{res.body}\n"
end

  




