#!/bin/bash

# wget a URL then make an ni name for that

if [ "$1" == "" ]
then
	echo "Usage: nameurl [-wh] <url>, where <url> is an http URL"
	echo "	default: ni: URI output" 
	echo "	-w gets a .well-known URL"
	echo "	-h gets an nih: URI"
	echo "	-b gets an binary equivalent"
	exit
fi

wanted=1 # 1 = ni, 2 = nih, 3 = .wel-known, 4 = bin

if [ "$1" == "-w" ]
then
	url=$2
	wanted=3
else
	if [ "$1" == "-h" ]
	then
		url=$2
		wanted=2
	else
		if [ "$1" == "-b" ]
		then
			url=$2
			wanted=4
		else
			if [ "$1" != "" ]
			then 
				url=$1
				wanted=1
			fi
		fi
	fi
fi

wget -o /tmp/nameurl.log -O /tmp/nameurl.content $url

niname=`../c/nicl -g -n "ni:///sha-256;?loc=$url" -f /tmp/nameurl.content`
nihname=`../c/nicl -g -n "nih:sha-256" -f /tmp/nameurl.content`
binname=`../c/nicl -b -s 1 -f /tmp/nameurl.content`


# that'll look like
# ni:///sha-256;Ui9dy6UyVYB8x2_ULYCjaIdwkPcBFGgmWtoEQhtqHTw?loc=http://www.rte.ie/

# make a .well-known

# this won't work (well) with http://user:password@authority/path but who cares
authority=`echo $url | cut -d'/' -f3 `
digest=`echo $niname | cut -d';' -f2 | cut -d'?' -f1`

wku="http://$authority/.well-known/ni/sha-256/"$digest

if [ "$wanted" == "1" ]
then
	echo $niname
fi
if [ "$wanted" == "2" ]
then
	echo $nihname
fi
if [ "$wanted" == "3" ]
then
	echo $wku
fi
if [ "$wanted" == "4" ]
then
	echo $binname
fi


