#!/bin/bash
# zap the netinf filesys node here

# set -x

cd /var/netinf/filesys/cache/meta_dir
rm -rf sha-256
sudo -u www-data mkdir sha-256
cd /var/netinf/filesys/cache/ndo_dir
rm -rf sha-256
sudo -u www-data mkdir sha-256
rm /var/netinf/filesys/log/log_mod_wsgi
service rsyslog restart
/etc/init.d/apache2 restart
cd /tmp
wget http://filesys.netinf.eu/netinfproto/checkcache
